###
# Get Books data
###
GET http://localhost:4004/odata/v4/book-store/Books
 
 
###
# Get Authors data
###
GET http://localhost:4004/odata/v4/book-store/Authors
 
###
# Create Author
###
POST http://localhost:4004/odata/v4/book-store/Authors
Content-Type: application/json
 
{"authorName": "J.K.Rowling", "address": "France","A_ID":"4","pincode":678765}
 
 
# ###
# # Get Top-rated Book
# ###
# GET http://localhost:4004/odata/v4/book-store/getPopularBook()
 
# ###
# # Rate Book
# ###
# POST http://localhost:4004/odata/v4/book-store/rateBook
# Content-Type: application/json
 
#     {
#         "bookID": "1",
#         "rating": 10
#     }